import * as React from "react";
import {
  Search,
  Download,
  LogIn,
  LogOut,
  Clock,
  XCircle,
  CheckCircle,
  Shield,
  Timer,
  UserX,
  MonitorSmartphone,
  Calendar,
  ChevronDown,
  Filter,
  X,
} from "lucide-react";
import {
  format,
  subDays,
  startOfDay,
  endOfDay,
  startOfMonth,
} from "date-fns";
import { ICON_STROKE_WIDTH } from "../../lib/constants";
import { Button } from "../../app/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../../app/components/ui/card";
import { Input } from "../../app/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../../app/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../app/components/ui/table";
import { Badge } from "../../app/components/ui/badge";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "../../app/components/ui/popover";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "../../app/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "../../app/components/ui/sheet";
import { PageShell } from "../../app/components/layouts/page-shell";
import { PageHeader } from "../../app/components/blocks/page-header";
import { BackButton } from "../../app/components/blocks/back-button";
import { StatCard } from "../../app/components/cards/stat-card";
import { Pagination } from "../../app/components/ui/pagination";
import { DateRangePicker } from "../../app/components/ui/date-range-picker";
import {
  Tabs,
  TabsList,
  TabsTrigger,
} from "../../app/components/ui/tabs";
import { FailedAttemptsTab } from "./FailedAttemptsTab";
import { ReportsTab } from "./ReportsTab";

/**
 * LOGIN & LOGOUT LOGS - Audit of User Login & Logout
 *
 * Story 1: Audit of User Login & Logout
 *
 * RBAC RULES:
 * - Only Admin & Compliance roles can view audit logs
 * - Facility Admin sees only their facility data
 * - Super Admin sees cross-facility data
 *
 * SCOPE:
 * ✔ Login
 * ✔ Logout
 * ✔ Login failure
 * ✔ Session timeout
 * ✔ Forced logout (admin / password reset / policy)
 * ✔ Concurrent Session Blocked (if enabled)
 *
 * DATA INTEGRITY:
 * - Audit logs are immutable
 * - No edit or delete allowed
 * - Timestamp auto-generated by server
 *
 * EVENT CONSISTENCY:
 * - Logout timestamp must be >= login timestamp
 * - Session duration auto-calculated
 * - Every successful login must have a corresponding logout or timeout
 *
 * COMPLIANCE:
 * - Supports NABH, ISO 27001, HIPAA-aligned security controls
 * - Logs retained for 5-7 years per retention policy
 * - Immutable - no edit or delete allowed
 * - Complete audit trail available for inspections
 *
 * NON-FUNCTIONAL REQUIREMENTS:
 * - Search results load <= 3 seconds
 * - Export supported (CSV / PDF) for audits
 *
 * BACKEND INTEGRATION NOTES:
 * - GET /api/admin/audit-logs/login-logout - List logs with pagination
 * - Query params: user, role, eventType, status, deviceType, dateFrom, dateTo, sessionId, ipAddress
 * - GET /api/admin/audit-logs/login-logout/export - Export logs as CSV/PDF
 * - Facility Admin sees only their facility; Super Admin sees cross-facility
 */

// --- Types ---

type EventType =
  | "Successful Login"
  | "Failed Login"
  | "Logout"
  | "Session Timeout"
  | "Forced Logout"
  | "Concurrent Session Blocked";

type EventStatus = "Success" | "Failure";
type UserRole =
  | "Radiologist"
  | "Technician"
  | "Front Desk"
  | "Facility Admin";
type DeviceType = "Web" | "Mobile" | "Workstation";
type AuthMethod = "Password" | "SSO" | "OTP";

interface LoginLogoutLog {
  auditId: string;
  userId: string;
  username: string;
  role: UserRole;
  facilityId: string;
  eventType: EventType;
  eventStatus: EventStatus;
  loginTimestamp: string;
  logoutTimestamp: string | null;
  sessionDuration: string | null;
  ipAddress: string;
  browserOs: string;
  authMethod: AuthMethod;
  failureReason: string | null;
  performedBy: string;
  sessionId: string | null;
  deviceType: DeviceType;
}

// --- Mock Data ---

const mockLoginLogoutLogs: LoginLogoutLog[] = [
  // ── Jan 15 ──────────────────────────────────────────
  {
    auditId: "AUD-10001",
    userId: "USR-001",
    username: "sarah.johnson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 07:58:11",
    logoutTimestamp: "2025-01-15 17:22:04",
    sessionDuration: "9h 23m",
    ipAddress: "192.168.1.100",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-89001",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10002",
    userId: "USR-002",
    username: "michael.chen",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 07:45:33",
    logoutTimestamp: "2025-01-15 16:30:18",
    sessionDuration: "8h 44m",
    ipAddress: "192.168.1.102",
    browserOs: "Firefox 122 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-89002",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10003",
    userId: "UNKNOWN",
    username: "admin_test",
    role: "Facility Admin",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-15 03:22:07",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "203.0.113.45",
    browserOs: "Chrome 120 / Linux",
    authMethod: "Password",
    failureReason: "Invalid credentials (3rd attempt)",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10004",
    userId: "USR-004",
    username: "david.kumar",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 14:10:05",
    logoutTimestamp: "2025-01-15 14:40:05",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.1.103",
    browserOs: "Edge 120 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-89003",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10005",
    userId: "USR-003",
    username: "emily.wong",
    role: "Radiologist",
    facilityId: "FAC-002",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 06:30:00",
    logoutTimestamp: "2025-01-15 12:45:22",
    sessionDuration: "6h 15m",
    ipAddress: "192.168.2.50",
    browserOs: "Safari 17 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "emily.wong",
    sessionId: "SES-89004",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10006",
    userId: "USR-008",
    username: "james.park",
    role: "Facility Admin",
    facilityId: "FAC-001",
    eventType: "Forced Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 09:00:00",
    logoutTimestamp: "2025-01-15 11:22:48",
    sessionDuration: "2h 22m",
    ipAddress: "192.168.1.105",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "super.admin",
    sessionId: "SES-89005",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10007",
    userId: "USR-006",
    username: "robert.anderson",
    role: "Front Desk",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 07:55:12",
    logoutTimestamp: "2025-01-15 16:00:45",
    sessionDuration: "8h 5m",
    ipAddress: "192.168.1.104",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-89006",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10008",
    userId: "UNKNOWN",
    username: "jsmith",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-15 06:12:55",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "192.168.1.110",
    browserOs: "Chrome 121 / Android 14",
    authMethod: "OTP",
    failureReason: "Account locked after 5 failed attempts",
    performedBy: "System",
    sessionId: null,
    deviceType: "Mobile",
  },
  {
    auditId: "AUD-10009",
    userId: "USR-005",
    username: "lisa.martinez",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-15 08:30:44",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "192.168.2.60",
    browserOs: "Safari 17 / iOS 17",
    authMethod: "OTP",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-89007",
    deviceType: "Mobile",
  },
  {
    auditId: "AUD-10010",
    userId: "USR-009",
    username: "tom.wilson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Concurrent Session Blocked",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-15 09:15:30",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "10.0.0.55",
    browserOs: "Firefox 122 / Windows 11",
    authMethod: "SSO",
    failureReason: "Active session exists on another device",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  // ── Jan 14 ──────────────────────────────────────────
  {
    auditId: "AUD-10011",
    userId: "USR-007",
    username: "priya.sharma",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 10:05:18",
    logoutTimestamp: "2025-01-14 10:35:18",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.1.108",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88920",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10012",
    userId: "USR-001",
    username: "sarah.johnson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Forced Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 08:00:00",
    logoutTimestamp: "2025-01-14 10:15:33",
    sessionDuration: "2h 15m",
    ipAddress: "192.168.1.100",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "james.park (Password Reset)",
    sessionId: "SES-88910",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10013",
    userId: "UNKNOWN",
    username: "root",
    role: "Facility Admin",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-14 02:47:19",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "198.51.100.78",
    browserOs: "curl/7.88 / Linux",
    authMethod: "Password",
    failureReason: "User does not exist",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10014",
    userId: "USR-010",
    username: "john.smith",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 09:00:08",
    logoutTimestamp: "2025-01-14 17:30:00",
    sessionDuration: "8h 29m",
    ipAddress: "192.168.1.112",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88915",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10015",
    userId: "USR-003",
    username: "emily.wong",
    role: "Radiologist",
    facilityId: "FAC-002",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 13:00:11",
    logoutTimestamp: "2025-01-14 19:10:55",
    sessionDuration: "6h 10m",
    ipAddress: "192.168.2.50",
    browserOs: "Safari 17 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88930",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10016",
    userId: "USR-006",
    username: "robert.anderson",
    role: "Front Desk",
    facilityId: "FAC-001",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 08:00:22",
    logoutTimestamp: "2025-01-14 16:05:10",
    sessionDuration: "8h 4m",
    ipAddress: "192.168.1.104",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "robert.anderson",
    sessionId: "SES-88905",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10017",
    userId: "UNKNOWN",
    username: "sarah.johnson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-14 07:58:02",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "192.168.1.100",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "Password",
    failureReason: "Invalid password (1st attempt)",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10018",
    userId: "USR-011",
    username: "kevin.lee",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 11:22:00",
    logoutTimestamp: "2025-01-14 11:52:00",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.2.75",
    browserOs: "Edge 120 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88925",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10019",
    userId: "USR-012",
    username: "anita.desai",
    role: "Radiologist",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 06:48:30",
    logoutTimestamp: "2025-01-14 15:12:09",
    sessionDuration: "8h 23m",
    ipAddress: "10.10.3.20",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88900",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10020",
    userId: "USR-013",
    username: "carlos.reyes",
    role: "Front Desk",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-14 07:30:00",
    logoutTimestamp: "2025-01-14 15:35:22",
    sessionDuration: "8h 5m",
    ipAddress: "10.10.3.25",
    browserOs: "Firefox 122 / Ubuntu 22.04",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88902",
    deviceType: "Workstation",
  },
  // ── Jan 13 ──────────────────────────────────────────
  {
    auditId: "AUD-10021",
    userId: "USR-014",
    username: "nina.patel",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 08:15:22",
    logoutTimestamp: "2025-01-13 16:45:10",
    sessionDuration: "8h 29m",
    ipAddress: "192.168.2.80",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88800",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10022",
    userId: "USR-015",
    username: "mark.taylor",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 07:00:15",
    logoutTimestamp: "2025-01-13 18:02:33",
    sessionDuration: "11h 2m",
    ipAddress: "192.168.1.115",
    browserOs: "Safari 17 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "mark.taylor",
    sessionId: "SES-88801",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10023",
    userId: "UNKNOWN",
    username: "hacker_bot",
    role: "Facility Admin",
    facilityId: "FAC-002",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-13 01:14:59",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "45.33.32.156",
    browserOs: "Python-urllib/3.11 / Linux",
    authMethod: "Password",
    failureReason: "IP blocked — rate limit exceeded",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10024",
    userId: "USR-016",
    username: "olivia.brown",
    role: "Front Desk",
    facilityId: "FAC-002",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 13:45:00",
    logoutTimestamp: "2025-01-13 14:15:00",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.2.85",
    browserOs: "Edge 120 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88810",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10025",
    userId: "USR-002",
    username: "michael.chen",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Forced Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 08:00:00",
    logoutTimestamp: "2025-01-13 09:45:12",
    sessionDuration: "1h 45m",
    ipAddress: "192.168.1.102",
    browserOs: "Firefox 122 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "james.park (Security Policy)",
    sessionId: "SES-88802",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10026",
    userId: "USR-017",
    username: "rachel.green",
    role: "Technician",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 09:10:55",
    logoutTimestamp: "2025-01-13 17:40:30",
    sessionDuration: "8h 29m",
    ipAddress: "10.10.3.30",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "OTP",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88820",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10027",
    userId: "USR-009",
    username: "tom.wilson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 07:30:40",
    logoutTimestamp: "2025-01-13 15:55:08",
    sessionDuration: "8h 24m",
    ipAddress: "10.0.0.55",
    browserOs: "Firefox 122 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88803",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10028",
    userId: "USR-005",
    username: "lisa.martinez",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 08:20:11",
    logoutTimestamp: "2025-01-13 14:50:48",
    sessionDuration: "6h 30m",
    ipAddress: "192.168.2.60",
    browserOs: "Safari 17 / iOS 17",
    authMethod: "OTP",
    failureReason: null,
    performedBy: "lisa.martinez",
    sessionId: "SES-88830",
    deviceType: "Mobile",
  },
  {
    auditId: "AUD-10029",
    userId: "UNKNOWN",
    username: "michael.chen",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-13 07:55:22",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "192.168.1.102",
    browserOs: "Firefox 122 / macOS 14",
    authMethod: "SSO",
    failureReason:
      "SSO token expired — re-authentication required",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10030",
    userId: "USR-018",
    username: "daniel.garcia",
    role: "Facility Admin",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-13 06:50:03",
    logoutTimestamp: "2025-01-13 18:22:17",
    sessionDuration: "11h 32m",
    ipAddress: "10.10.3.10",
    browserOs: "Chrome 121 / macOS 14",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88804",
    deviceType: "Web",
  },
  // ── Jan 12 ──────────────────────────────────────────
  {
    auditId: "AUD-10031",
    userId: "USR-019",
    username: "sophia.nguyen",
    role: "Radiologist",
    facilityId: "FAC-002",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 08:05:44",
    logoutTimestamp: "2025-01-12 17:18:09",
    sessionDuration: "9h 12m",
    ipAddress: "192.168.2.90",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88700",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10032",
    userId: "USR-020",
    username: "ryan.murphy",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 15:00:00",
    logoutTimestamp: "2025-01-12 15:30:00",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.1.120",
    browserOs: "Edge 120 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88710",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10033",
    userId: "USR-008",
    username: "james.park",
    role: "Facility Admin",
    facilityId: "FAC-001",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 07:00:00",
    logoutTimestamp: "2025-01-12 19:05:30",
    sessionDuration: "12h 5m",
    ipAddress: "192.168.1.105",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "james.park",
    sessionId: "SES-88701",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10034",
    userId: "USR-012",
    username: "anita.desai",
    role: "Radiologist",
    facilityId: "FAC-003",
    eventType: "Concurrent Session Blocked",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-12 10:30:45",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "10.10.3.20",
    browserOs: "Safari 17 / iOS 17",
    authMethod: "SSO",
    failureReason: "Active session exists on another device",
    performedBy: "System",
    sessionId: null,
    deviceType: "Mobile",
  },
  {
    auditId: "AUD-10035",
    userId: "UNKNOWN",
    username: "test.user",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-12 04:33:18",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "172.16.0.99",
    browserOs: "Postman/10.0 / Windows 11",
    authMethod: "Password",
    failureReason: "Account disabled by administrator",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10036",
    userId: "USR-013",
    username: "carlos.reyes",
    role: "Front Desk",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 07:45:55",
    logoutTimestamp: "2025-01-12 16:10:30",
    sessionDuration: "8h 24m",
    ipAddress: "10.10.3.25",
    browserOs: "Firefox 122 / Ubuntu 22.04",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88720",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10037",
    userId: "USR-004",
    username: "david.kumar",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 08:22:10",
    logoutTimestamp: "2025-01-12 17:00:00",
    sessionDuration: "8h 37m",
    ipAddress: "192.168.1.103",
    browserOs: "Edge 120 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88730",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10038",
    userId: "USR-016",
    username: "olivia.brown",
    role: "Front Desk",
    facilityId: "FAC-002",
    eventType: "Forced Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 08:00:12",
    logoutTimestamp: "2025-01-12 09:15:44",
    sessionDuration: "1h 15m",
    ipAddress: "192.168.2.85",
    browserOs: "Edge 120 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "daniel.garcia (Shift Change)",
    sessionId: "SES-88740",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10039",
    userId: "USR-001",
    username: "sarah.johnson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 07:10:00",
    logoutTimestamp: "2025-01-12 16:50:22",
    sessionDuration: "9h 40m",
    ipAddress: "192.168.1.100",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "sarah.johnson",
    sessionId: "SES-88702",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10040",
    userId: "USR-021",
    username: "hannah.kim",
    role: "Technician",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-12 09:00:33",
    logoutTimestamp: "2025-01-12 17:25:12",
    sessionDuration: "8h 24m",
    ipAddress: "10.10.3.35",
    browserOs: "Chrome 121 / ChromeOS 120",
    authMethod: "OTP",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88750",
    deviceType: "Web",
  },
  // ── Jan 11 ──────────────────────────────────────────
  {
    auditId: "AUD-10041",
    userId: "USR-022",
    username: "alex.thompson",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 07:20:18",
    logoutTimestamp: "2025-01-11 16:48:55",
    sessionDuration: "9h 28m",
    ipAddress: "192.168.1.130",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88600",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10042",
    userId: "USR-014",
    username: "nina.patel",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Session Timeout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 14:30:00",
    logoutTimestamp: "2025-01-11 15:00:00",
    sessionDuration: "30m 0s",
    ipAddress: "192.168.2.80",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88610",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10043",
    userId: "UNKNOWN",
    username: "admin",
    role: "Facility Admin",
    facilityId: "FAC-003",
    eventType: "Failed Login",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-11 23:45:10",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "185.220.101.42",
    browserOs: "Scrapy/2.11 / Linux",
    authMethod: "Password",
    failureReason:
      "Brute-force detected — IP temporarily blocked",
    performedBy: "System",
    sessionId: null,
    deviceType: "Web",
  },
  {
    auditId: "AUD-10044",
    userId: "USR-015",
    username: "mark.taylor",
    role: "Radiologist",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 06:55:09",
    logoutTimestamp: "2025-01-11 17:30:42",
    sessionDuration: "10h 35m",
    ipAddress: "192.168.1.115",
    browserOs: "Safari 17 / macOS 14",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88601",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10045",
    userId: "USR-017",
    username: "rachel.green",
    role: "Technician",
    facilityId: "FAC-003",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 08:50:20",
    logoutTimestamp: "2025-01-11 17:05:18",
    sessionDuration: "8h 14m",
    ipAddress: "10.10.3.30",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "OTP",
    failureReason: null,
    performedBy: "rachel.green",
    sessionId: "SES-88620",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10046",
    userId: "USR-006",
    username: "robert.anderson",
    role: "Front Desk",
    facilityId: "FAC-001",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 07:50:00",
    logoutTimestamp: "2025-01-11 16:15:33",
    sessionDuration: "8h 25m",
    ipAddress: "192.168.1.104",
    browserOs: "Chrome 121 / Windows 10",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88602",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10047",
    userId: "USR-019",
    username: "sophia.nguyen",
    role: "Radiologist",
    facilityId: "FAC-002",
    eventType: "Forced Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 08:00:00",
    logoutTimestamp: "2025-01-11 10:30:22",
    sessionDuration: "2h 30m",
    ipAddress: "192.168.2.90",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "SSO",
    failureReason: null,
    performedBy: "super.admin (Emergency Maintenance)",
    sessionId: "SES-88630",
    deviceType: "Web",
  },
  {
    auditId: "AUD-10048",
    userId: "USR-011",
    username: "kevin.lee",
    role: "Technician",
    facilityId: "FAC-002",
    eventType: "Concurrent Session Blocked",
    eventStatus: "Failure",
    loginTimestamp: "2025-01-11 12:10:15",
    logoutTimestamp: null,
    sessionDuration: null,
    ipAddress: "192.168.2.75",
    browserOs: "Chrome 121 / Android 14",
    authMethod: "OTP",
    failureReason: "Active session exists on another device",
    performedBy: "System",
    sessionId: null,
    deviceType: "Mobile",
  },
  {
    auditId: "AUD-10049",
    userId: "USR-010",
    username: "john.smith",
    role: "Technician",
    facilityId: "FAC-001",
    eventType: "Logout",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 08:30:00",
    logoutTimestamp: "2025-01-11 17:10:48",
    sessionDuration: "8h 40m",
    ipAddress: "192.168.1.112",
    browserOs: "Chrome 121 / Windows 11",
    authMethod: "Password",
    failureReason: null,
    performedBy: "john.smith",
    sessionId: "SES-88640",
    deviceType: "Workstation",
  },
  {
    auditId: "AUD-10050",
    userId: "USR-018",
    username: "daniel.garcia",
    role: "Facility Admin",
    facilityId: "FAC-003",
    eventType: "Successful Login",
    eventStatus: "Success",
    loginTimestamp: "2025-01-11 07:00:50",
    logoutTimestamp: "2025-01-11 19:45:00",
    sessionDuration: "12h 44m",
    ipAddress: "10.10.3.10",
    browserOs: "Chrome 121 / macOS 14",
    authMethod: "Password",
    failureReason: null,
    performedBy: "System",
    sessionId: "SES-88603",
    deviceType: "Web",
  },
];

// --- Component ---

export function LoginLogoutLogs() {
  const [logs] = React.useState<LoginLogoutLog[]>(
    mockLoginLogoutLogs,
  );
  const [usernameFilter, setUsernameFilter] =
    React.useState("");
  const [eventTypeFilter, setEventTypeFilter] =
    React.useState("all");
  const [statusFilter, setStatusFilter] = React.useState("all");
  const [roleFilter, setRoleFilter] = React.useState("all");
  const [deviceFilter, setDeviceFilter] = React.useState("all");
  const [ipSessionFilter, setIpSessionFilter] =
    React.useState("");

  // Date range filter state
  const [datePickerOpen, setDatePickerOpen] =
    React.useState(false);
  const [dateRange, setDateRange] = React.useState<{
    from: Date;
    to: Date;
  }>({
    from: subDays(new Date(), 450),
    to: new Date(),
  });
  const [tempDateRange, setTempDateRange] = React.useState<{
    from?: Date;
    to?: Date;
  }>({});
  // Tracks whether the user has actively applied a date filter
  const [isDateRangeActive, setIsDateRangeActive] =
    React.useState(false);

  // Active header tab
  const [activeTab, setActiveTab] = React.useState("overview");

  // Filter bar visibility — open by default
  const [showFilters, setShowFilters] = React.useState(true);

  // Row detail dialog
  const [selectedLog, setSelectedLog] =
    React.useState<LoginLogoutLog | null>(null);
  const [detailOpen, setDetailOpen] = React.useState(false);

  // Pagination
  const [currentPage, setCurrentPage] = React.useState(1);
  const [itemsPerPage] = React.useState(10);

  // Quick date ranges
  const quickRanges = [
    {
      label: "Today",
      getValue: () => ({
        from: startOfDay(new Date()),
        to: endOfDay(new Date()),
      }),
    },
    {
      label: "Last 7 days",
      getValue: () => ({
        from: subDays(new Date(), 7),
        to: new Date(),
      }),
    },
    {
      label: "Last 30 days",
      getValue: () => ({
        from: subDays(new Date(), 30),
        to: new Date(),
      }),
    },
    {
      label: "Last 90 days",
      getValue: () => ({
        from: subDays(new Date(), 90),
        to: new Date(),
      }),
    },
    {
      label: "Month to date",
      getValue: () => ({
        from: startOfMonth(new Date()),
        to: new Date(),
      }),
    },
  ];

  const handleCancelDateRange = () => {
    setTempDateRange({});
    setDatePickerOpen(false);
  };

  // Stats
  const stats = React.useMemo(() => {
    const totalEvents = logs.length;
    const successfulLogins = logs.filter(
      (l) => l.eventType === "Successful Login",
    ).length;
    const failedLogins = logs.filter(
      (l) =>
        l.eventType === "Failed Login" ||
        l.eventType === "Concurrent Session Blocked",
    ).length;
    const sessionTimeouts = logs.filter(
      (l) => l.eventType === "Session Timeout",
    ).length;
    const forcedLogouts = logs.filter(
      (l) => l.eventType === "Forced Logout",
    ).length;
    return {
      totalEvents,
      successfulLogins,
      failedLogins,
      sessionTimeouts,
      forcedLogouts,
    };
  }, [logs]);

  // Filtered logs — each filter is independently AND'd per document spec
  const filteredLogs = React.useMemo(() => {
    return logs.filter((log) => {
      // Filter 3: Username / UHID
      const uq = usernameFilter.toLowerCase();
      const matchesUsername =
        !uq ||
        log.username.toLowerCase().includes(uq) ||
        log.userId.toLowerCase().includes(uq);

      // Filter 4: Event Type
      const matchesEventType =
        eventTypeFilter === "all" ||
        log.eventType === eventTypeFilter;

      // Filter 7: Status
      const matchesStatus =
        statusFilter === "all" ||
        log.eventStatus === statusFilter;

      // Filter 2: User Role
      const matchesRole =
        roleFilter === "all" || log.role === roleFilter;

      // Filter 6: Device Type
      const matchesDevice =
        deviceFilter === "all" ||
        log.deviceType === deviceFilter;

      // Filter 5 & 8: IP Address OR Session ID (combined search)
      const ipSessionTerm = ipSessionFilter.toLowerCase();
      const matchesIpSession =
        !ipSessionTerm ||
        log.ipAddress.toLowerCase().includes(ipSessionTerm) ||
        (log.sessionId !== null &&
          log.sessionId.toLowerCase().includes(ipSessionTerm));

      // Filter 1: Date & Time Range
      const logDate = new Date(log.loginTimestamp);
      const matchesDate =
        logDate >= startOfDay(dateRange.from) &&
        logDate <= endOfDay(dateRange.to);

      return (
        matchesUsername &&
        matchesEventType &&
        matchesStatus &&
        matchesRole &&
        matchesDevice &&
        matchesIpSession &&
        matchesDate
      );
    });
  }, [
    logs,
    usernameFilter,
    eventTypeFilter,
    statusFilter,
    roleFilter,
    deviceFilter,
    dateRange,
    ipSessionFilter,
  ]);

  // Pagination
  const totalPages = Math.max(
    1,
    Math.ceil(filteredLogs.length / itemsPerPage),
  );
  const paginatedLogs = React.useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return filteredLogs.slice(start, start + itemsPerPage);
  }, [filteredLogs, currentPage, itemsPerPage]);

  // Reset page on filter change
  React.useEffect(() => {
    setCurrentPage(1);
  }, [
    usernameFilter,
    eventTypeFilter,
    statusFilter,
    roleFilter,
    deviceFilter,
    dateRange,
    ipSessionFilter,
  ]);

  // Export / Reports sheet
  const [reportSheetOpen, setReportSheetOpen] = React.useState(false);
  const handleExport = () => setReportSheetOpen(true);

  // Filter helpers
  const hasActiveFilters =
    eventTypeFilter !== "all" ||
    statusFilter !== "all" ||
    roleFilter !== "all" ||
    deviceFilter !== "all" ||
    ipSessionFilter !== "";

  const clearAllFilters = () => {
    setEventTypeFilter("all");
    setStatusFilter("all");
    setRoleFilter("all");
    setDeviceFilter("all");
    setIpSessionFilter("");
    setUsernameFilter("");
  };

  // Open detail dialog
  const handleRowClick = (log: LoginLogoutLog) => {
    setSelectedLog(log);
    setDetailOpen(true);
  };

  // --- Badge / icon helpers ---

  const getEventTypeBadge = (eventType: EventType) => {
    switch (eventType) {
      case "Successful Login":
        return (
          <Badge variant="default">
            <LogIn
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Login
          </Badge>
        );
      case "Failed Login":
        return (
          <Badge variant="destructive">
            <XCircle
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Failed Login
          </Badge>
        );
      case "Logout":
        return (
          <Badge variant="outline">
            <LogOut
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Logout
          </Badge>
        );
      case "Session Timeout":
        return (
          <Badge variant="outline">
            <Timer
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Timeout
          </Badge>
        );
      case "Forced Logout":
        return (
          <Badge variant="outline">
            <UserX
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Forced Logout
          </Badge>
        );
      case "Concurrent Session Blocked":
        return (
          <Badge variant="destructive">
            <MonitorSmartphone
              className="size-3 mr-1"
              strokeWidth={ICON_STROKE_WIDTH}
            />
            Blocked
          </Badge>
        );
    }
  };

  const getStatusIcon = (status: EventStatus) => {
    switch (status) {
      case "Success":
        return (
          <CheckCircle
            strokeWidth={ICON_STROKE_WIDTH}
            className="size-4 text-primary"
          />
        );
      case "Failure":
        return (
          <XCircle
            strokeWidth={ICON_STROKE_WIDTH}
            className="size-4 text-destructive"
          />
        );
    }
  };

  const getRoleBadge = (role: UserRole) => {
    return <Badge variant="secondary">{role}</Badge>;
  };

  // --- Detail row component for the dialog ---

  const DetailRow = ({
    label,
    value,
    mono,
  }: {
    label: string;
    value: React.ReactNode;
    mono?: boolean;
  }) => (
    <div className="flex items-start py-2.5 border-b border-border last:border-0">
      <span className="w-40 shrink-0 text-xs text-muted-foreground">
        {label}
      </span>
      <span
        className={`text-sm flex-1 ${mono ? "roboto-mono text-xs tabular-nums" : ""}`}
      >
        {value ?? (
          <span className="text-muted-foreground">—</span>
        )}
      </span>
    </div>
  );

  return (
    <PageShell>
      <PageHeader
        title="Login & Logout Logs"
        noBorder
        leading={<BackButton href="/admin/audit-logs" />}
        actions={
          <Button onClick={handleExport}>
            <Download
              strokeWidth={ICON_STROKE_WIDTH}
              className="mr-2 size-4"
            />
            Export Logs
          </Button>
        }
      />

      {/* Line tabs — sits flush below the page header, above the scroll area */}
      <div className="sticky top-14 z-30 bg-background border-b border-border pl-2 pr-6">
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList variant="line">
            <TabsTrigger value="overview">User Details</TabsTrigger>
            <TabsTrigger value="analytics">Failed Attempts</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      <div className="flex-1 overflow-auto">
        {activeTab === "analytics" && <FailedAttemptsTab />}
        {activeTab === "overview" && (
        <div className="container mx-auto max-w-7xl px-6 py-6 space-y-6">
          {/* Stats Cards */}
          <div className="grid gap-4 md:grid-cols-5">
            <StatCard
              title="Manual Logout"
              value={stats.totalEvents}
              description="Last 24 hours"
              icon={LogIn}
              iconStrokeWidth={ICON_STROKE_WIDTH}
              iconColor="text-primary"
            />
            <StatCard
              title="Successful Logins"
              value={stats.successfulLogins}
              description={`${Math.round(
                (stats.successfulLogins / stats.totalEvents) *
                  100,
              )}% of events`}
              icon={CheckCircle}
              iconStrokeWidth={ICON_STROKE_WIDTH}
              iconColor="text-primary"
            />
            <StatCard
              title="Failed Attempts"
              value={stats.failedLogins}
              description="Requires investigation"
              icon={XCircle}
              iconStrokeWidth={ICON_STROKE_WIDTH}
              iconColor="text-destructive"
            />
            <StatCard
              title="Session Timeouts"
              value={stats.sessionTimeouts}
              description="Auto-logged out"
              icon={Clock}
              iconStrokeWidth={ICON_STROKE_WIDTH}
              iconColor="text-muted-foreground"
            />
            <StatCard
              title="Forced Logouts"
              value={stats.forcedLogouts}
              description="Admin / policy driven"
              icon={UserX}
              iconStrokeWidth={ICON_STROKE_WIDTH}
              iconColor="text-destructive"
            />
          </div>

          {/* Logs Table */}
          <Card className="px-[16px] py-[0px] p-[16px]">
            <div className="flex flex-col gap-3 p-[0px]">
              {/* Row 1: Date + Search | Download CSV + Filter icon */}
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  {/* Date Range Picker — calendar icon on RIGHT (§2.1) */}
                  <Popover
                    open={datePickerOpen}
                    onOpenChange={setDatePickerOpen}
                  >
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={[
                          "w-48 justify-between gap-2 font-normal",
                          isDateRangeActive
                            ? "bg-primary/10 border-primary text-primary hover:bg-primary/15"
                            : "bg-background border-border",
                        ].join(" ")}
                      >
                        <span
                          className={[
                            "text-sm",
                            isDateRangeActive
                              ? "text-primary"
                              : "text-muted-foreground",
                          ].join(" ")}
                        >
                          {format(dateRange.from, "MMM dd")} –{" "}
                          {format(dateRange.to, "MMM dd")}
                        </span>
                        {isDateRangeActive ? (
                          <X
                            className="size-4 text-primary shrink-0"
                            strokeWidth={ICON_STROKE_WIDTH}
                            onClick={(e) => {
                              e.stopPropagation();
                              // Reset all filters to default
                              setUsernameFilter("");
                              setIpSessionFilter("");
                              setEventTypeFilter("all");
                              setStatusFilter("all");
                              setRoleFilter("all");
                              setDeviceFilter("all");
                              setDateRange({
                                from: subDays(new Date(), 450),
                                to: new Date(),
                              });
                              setTempDateRange({});
                              setIsDateRangeActive(false);
                              setCurrentPage(1);
                            }}
                          />
                        ) : (
                          <Calendar
                            className="size-4 text-muted-foreground shrink-0"
                            strokeWidth={ICON_STROKE_WIDTH}
                          />
                        )}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent
                      className="w-auto p-0 border-0 shadow-none bg-transparent"
                      align="start"
                      sideOffset={4}
                    >
                      <DateRangePicker
                        value={tempDateRange}
                        quickRanges={quickRanges}
                        onApply={(range) => {
                          setDateRange(range);
                          setTempDateRange(range);
                          setIsDateRangeActive(true);
                          setDatePickerOpen(false);
                        }}
                        onCancel={handleCancelDateRange}
                      />
                    </PopoverContent>
                  </Popover>

                  {/* Unified search */}
                  <div className="bg-background relative rounded-[8px] w-80">
                    <div className="flex items-center gap-2 px-3 py-[7.5px]">
                      <Search
                        strokeWidth={ICON_STROKE_WIDTH}
                        className="size-5 text-muted-foreground shrink-0"
                      />
                      <input
                        placeholder="Search by username, UHID, IP address or Session ID"
                        value={usernameFilter}
                        onChange={(e) => {
                          setUsernameFilter(e.target.value);
                          setIpSessionFilter(e.target.value);
                        }}
                        className="flex-1 min-w-0 bg-transparent text-sm text-foreground placeholder:text-muted-foreground outline-none"
                      />
                    </div>
                    <div
                      aria-hidden="true"
                      className="absolute border border-border inset-[-1px] pointer-events-none rounded-[4px]"
                    />
                  </div>
                </div>

                {/* Right: Download CSV + filter icon */}
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="icon"
                    aria-label="Filter options"
                    aria-pressed={showFilters}
                    onClick={() => setShowFilters((v) => !v)}
                    className={
                      showFilters
                        ? "bg-accent text-accent-foreground border-border"
                        : ""
                    }
                  >
                    <Filter
                      className="size-4"
                      strokeWidth={ICON_STROKE_WIDTH}
                    />
                  </Button>
                </div>
              </div>

              {/* Row 2: Filter chips */}
              {showFilters && (
                <div className="flex items-center gap-2 flex-wrap">
                  {/* Event Type chip */}
                  <Select
                    value={eventTypeFilter}
                    onValueChange={setEventTypeFilter}
                  >
                    <SelectTrigger className="h-8 w-40 bg-card border-border text-foreground gap-1.5 px-3 rounded-[4px] font-medium hover:bg-accent data-[state=open]:bg-accent">
                      <SelectValue placeholder="Event Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">
                        All Event Types
                      </SelectItem>
                      <SelectItem value="Successful Login">
                        Successful Login
                      </SelectItem>
                      <SelectItem value="Failed Login">
                        Failed Login
                      </SelectItem>
                      <SelectItem value="Logout">
                        Logout
                      </SelectItem>
                      <SelectItem value="Session Timeout">
                        Session Timeout
                      </SelectItem>
                      <SelectItem value="Forced Logout">
                        Forced Logout
                      </SelectItem>
                      <SelectItem value="Concurrent Session Blocked">
                        Session Blocked
                      </SelectItem>
                    </SelectContent>
                  </Select>

                  {/* Status chip */}
                  <Select
                    value={statusFilter}
                    onValueChange={setStatusFilter}
                  >
                    <SelectTrigger className="h-8 w-32 bg-card border-border text-foreground gap-1.5 px-3 rounded-[4px] font-medium hover:bg-accent data-[state=open]:bg-accent">
                      <SelectValue placeholder="Status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">
                        All Statuses
                      </SelectItem>
                      <SelectItem value="Success">
                        Success
                      </SelectItem>
                      <SelectItem value="Failure">
                        Failure
                      </SelectItem>
                    </SelectContent>
                  </Select>

                  {/* Role chip */}
                  <Select
                    value={roleFilter}
                    onValueChange={setRoleFilter}
                  >
                    <SelectTrigger className="h-8 w-36 bg-card border-border text-foreground gap-1.5 px-3 rounded-[4px] font-medium hover:bg-accent data-[state=open]:bg-accent">
                      <SelectValue placeholder="Role" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">
                        All Roles
                      </SelectItem>
                      <SelectItem value="Radiologist">
                        Radiologist
                      </SelectItem>
                      <SelectItem value="Technician">
                        Technician
                      </SelectItem>
                      <SelectItem value="Front Desk">
                        Front Desk
                      </SelectItem>
                      <SelectItem value="Facility Admin">
                        Facility Admin
                      </SelectItem>
                    </SelectContent>
                  </Select>

                  {/* Device chip */}
                  <Select
                    value={deviceFilter}
                    onValueChange={setDeviceFilter}
                  >
                    <SelectTrigger className="h-8 w-32 bg-card border-border text-foreground gap-1.5 px-3 rounded-[4px] font-medium hover:bg-accent data-[state=open]:bg-accent">
                      <SelectValue placeholder="Device" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">
                        All Devices
                      </SelectItem>
                      <SelectItem value="Web">Web</SelectItem>
                      <SelectItem value="Mobile">
                        Mobile
                      </SelectItem>
                      <SelectItem value="Workstation">
                        Workstation
                      </SelectItem>
                    </SelectContent>
                  </Select>

                  {/* Clear all — visible only when any filter is active */}
                  {hasActiveFilters && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-8 gap-1.5 px-3 bg-card border-border text-foreground font-medium hover:bg-accent rounded-[4px]"
                      onClick={clearAllFilters}
                      aria-label="Clear all filters"
                    >
                      <X
                        className="size-3.5 text-muted-foreground"
                        strokeWidth={ICON_STROKE_WIDTH}
                      />
                      Clear All
                    </Button>
                  )}
                </div>
              )}
            </div>

            <CardContent className="p-[0px]">
              <Table className="mb-2">
                <TableHeader>
                  <TableRow>
                    <TableHead className="whitespace-nowrap">
                      Audit ID
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      UHID
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Username
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Role
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Facility ID
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Event Type
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Event Status
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Login Timestamp
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Logout Timestamp
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Session Duration
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      IP Address
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Browser / OS
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Authentication Method
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Failure Reason
                    </TableHead>
                    <TableHead className="whitespace-nowrap">
                      Performed By
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {paginatedLogs.length > 0 ? (
                    paginatedLogs.map((log) => (
                      <TableRow
                        key={log.auditId}
                        className="hover:bg-muted/50"
                      >
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap">
                          {log.auditId}
                        </TableCell>
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap">
                          {log.userId}
                        </TableCell>
                        <TableCell className="text-sm whitespace-nowrap">
                          {log.username}
                        </TableCell>
                        <TableCell>
                          {getRoleBadge(log.role)}
                        </TableCell>
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap">
                          {log.facilityId}
                        </TableCell>
                        <TableCell>
                          {getEventTypeBadge(log.eventType)}
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            {getStatusIcon(log.eventStatus)}
                            <span className="text-sm whitespace-nowrap">
                              {log.eventStatus}
                            </span>
                          </div>
                        </TableCell>
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap font-[Roboto_Mono]">
                          {log.loginTimestamp}
                        </TableCell>
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap font-[Roboto_Mono]">
                          {log.logoutTimestamp ?? (
                            <span className="text-muted-foreground">
                              —
                            </span>
                          )}
                        </TableCell>
                        <TableCell className="text-sm whitespace-nowrap tabular-nums font-[Roboto_Mono]">
                          {log.sessionDuration ?? (
                            <span className="text-muted-foreground">
                              —
                            </span>
                          )}
                        </TableCell>
                        <TableCell className="roboto-mono text-sm tabular-nums whitespace-nowrap font-[Roboto_Mono]">
                          {log.ipAddress}
                        </TableCell>
                        <TableCell
                          className="text-xs whitespace-nowrap max-w-52 truncate"
                          title={log.browserOs}
                        >
                          {log.browserOs}
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">
                            {log.authMethod}
                          </Badge>
                        </TableCell>
                        <TableCell className="max-w-52">
                          {log.failureReason ? (
                            <span
                              className="text-xs text-destructive truncate block"
                              title={log.failureReason}
                            >
                              {log.failureReason}
                            </span>
                          ) : (
                            <span className="text-muted-foreground">
                              —
                            </span>
                          )}
                        </TableCell>
                        <TableCell className="text-sm whitespace-nowrap">
                          {log.performedBy}
                        </TableCell>
                      </TableRow>
                    ))
                  ) : (
                    <TableRow>
                      <TableCell
                        colSpan={15}
                        className="h-24 text-center"
                      >
                        <div className="flex flex-col items-center gap-2 py-8">
                          <Search
                            className="size-8 text-muted-foreground"
                            strokeWidth={ICON_STROKE_WIDTH}
                          />
                          <p className="text-sm text-muted-foreground">
                            No authentication logs found
                            matching your criteria
                          </p>
                          <p className="text-xs text-muted-foreground">
                            Try adjusting your filters or date
                            range.
                          </p>
                        </div>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>

              <div className="mt-2">
                <Pagination
                  currentPage={currentPage}
                  totalPages={totalPages}
                  totalItems={filteredLogs.length}
                  itemsPerPage={itemsPerPage}
                  onPageChange={setCurrentPage}
                />
              </div>

              {/* Compliance Notice */}
            </CardContent>
          </Card>
        </div>
        )}
      </div>

      {/* Row Detail Dialog — shows ALL 15 system-captured audit log fields */}
      <Dialog open={detailOpen} onOpenChange={setDetailOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              Audit Record Detail
              {selectedLog && (
                <span className="roboto-mono text-sm tabular-nums text-muted-foreground">
                  {selectedLog.auditId}
                </span>
              )}
            </DialogTitle>
            <DialogDescription>
              Complete authentication audit record — read-only,
              immutable
            </DialogDescription>
          </DialogHeader>

          {selectedLog && (
            <div className="mt-2">
              <DetailRow
                label="Audit ID"
                value={selectedLog.auditId}
                mono
              />
              <DetailRow
                label="UHID"
                value={selectedLog.userId}
                mono
              />
              <DetailRow
                label="Username"
                value={selectedLog.username}
              />
              <DetailRow
                label="Role"
                value={getRoleBadge(selectedLog.role)}
              />
              <DetailRow
                label="Facility ID"
                value={selectedLog.facilityId}
                mono
              />
              <DetailRow
                label="Event Type"
                value={getEventTypeBadge(selectedLog.eventType)}
              />
              <DetailRow
                label="Event Status"
                value={
                  <div className="flex items-center gap-2">
                    {getStatusIcon(selectedLog.eventStatus)}
                    <span>{selectedLog.eventStatus}</span>
                  </div>
                }
              />
              <DetailRow
                label="Login Timestamp"
                value={selectedLog.loginTimestamp}
                mono
              />
              <DetailRow
                label="Logout Timestamp"
                value={selectedLog.logoutTimestamp}
                mono
              />
              <DetailRow
                label="Session Duration"
                value={selectedLog.sessionDuration}
              />
              <DetailRow
                label="IP Address"
                value={selectedLog.ipAddress}
                mono
              />
              <DetailRow
                label="Browser / OS"
                value={selectedLog.browserOs}
              />
              <DetailRow
                label="Device Type"
                value={selectedLog.deviceType}
              />
              <DetailRow
                label="Auth Method"
                value={
                  <Badge variant="outline">
                    {selectedLog.authMethod}
                  </Badge>
                }
              />
              <DetailRow
                label="Session ID"
                value={selectedLog.sessionId}
                mono
              />
              <DetailRow
                label="Failure Reason"
                value={
                  selectedLog.failureReason ? (
                    <span className="text-destructive">
                      {selectedLog.failureReason}
                    </span>
                  ) : null
                }
              />
              <DetailRow
                label="Performed By"
                value={selectedLog.performedBy}
              />
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Export Logs Sheet — triggered by the Export Logs button in the page header */}
      <Sheet open={reportSheetOpen} onOpenChange={setReportSheetOpen}>
        <SheetContent
          side="right"
          className="w-full sm:max-w-2xl overflow-y-auto p-0"
        >
          <SheetHeader className="px-6 py-4 border-b border-border">
            <SheetTitle>Export Logs</SheetTitle>
            <SheetDescription>
              Generate and download compliance reports from immutable audit log data.
            </SheetDescription>
          </SheetHeader>
          <div className="overflow-y-auto">
            <ReportsTab />
          </div>
        </SheetContent>
      </Sheet>
    </PageShell>
  );
}

export default LoginLogoutLogs;